# Generated by Django 4.2.15 on 2024-12-11 08:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Classes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Recursos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(max_length=10)),
                ('descricao', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Pecas',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(max_length=10, unique=True)),
                ('nome', models.CharField(max_length=100)),
                ('unidade', models.CharField(default='Un', max_length=10)),
                ('class_fiscal', models.CharField(default='8716.90.90', max_length=20)),
                ('procedencia', models.CharField(default='Nacional - 0', max_length=50)),
                ('status', models.TextField()),
                ('tipo', models.CharField(choices=[('peca', 'Peça'), ('conjunto', 'Conjunto')])),
                ('classe', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pecas', to='cadastro.classes')),
            ],
        ),
        migrations.CreateModel(
            name='BlocoRecursos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ordem', models.IntegerField()),
                ('quantidade', models.FloatField()),
                ('dep_origem', models.CharField(choices=[('almox_pintura_embalagem', 'Almox Pintura'), ('almox_prod_especiais', 'Almox Prod Especiais'), ('almox_cx_acessorios', 'Almox Cx Acessórios'), ('almox_carpintaria', 'Almox Carpintaria'), ('almox_central', 'Almox Central'), ('almox_qualidade', 'Almox Qualidade'), ('almox_corte_estamparia', 'Almox Corte e Estamparia'), ('almox_prototipos', 'Almox Protótipos'), ('almox_serra', 'Almox Serra')], max_length=50)),
                ('peca', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recursos', to='cadastro.pecas')),
                ('recurso', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='codigo_recursos', to='cadastro.recursos')),
            ],
        ),
        migrations.CreateModel(
            name='BlocoPropriedade',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('propriedade', models.CharField(choices=[('comprimento', 'Comprimento')], max_length=20)),
                ('valor', models.FloatField()),
                ('peca', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='propriedades', to='cadastro.pecas')),
            ],
        ),
        migrations.CreateModel(
            name='BlocoEtapas',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ordem', models.IntegerField()),
                ('processo', models.CharField(choices=[('s_c_plasma', 'S C Plasma'), ('s_c_guilhotina', 'S C Guilhotina'), ('s_c_laser', 'S C Laser'), ('s_c_prensas', 'S C Prensas'), ('s_c_serras', 'S C Serras'), ('s_carpintaria', 'S Carpintaria'), ('s_corte_manual', 'S Corte Manual'), ('s_cx_acessorios', 'S Cx Acessórios'), ('s_desbobinar', 'S Desbobinar'), ('s_estamparia', 'S Estamparia'), ('s_expedicao', 'S Expedição'), ('s_forjaria', 'S Forjaria')], max_length=50)),
                ('descricao', models.CharField(max_length=20)),
                ('destino', models.CharField(choices=[('almox_pintura_embalagem', 'Almox Pintura'), ('almox_prod_especiais', 'Almox Prod Especiais'), ('almox_cx_acessorios', 'Almox Cx Acessórios'), ('almox_carpintaria', 'Almox Carpintaria'), ('almox_central', 'Almox Central'), ('almox_qualidade', 'Almox Qualidade'), ('almox_corte_estamparia', 'Almox Corte e Estamparia'), ('almox_prototipos', 'Almox Protótipos'), ('almox_serra', 'Almox Serra')], max_length=50)),
                ('desvio', models.CharField(choices=[('almox_pintura_embalagem', 'Almox Pintura'), ('almox_prod_especiais', 'Almox Prod Especiais'), ('almox_cx_acessorios', 'Almox Cx Acessórios'), ('almox_carpintaria', 'Almox Carpintaria'), ('almox_central', 'Almox Central'), ('almox_qualidade', 'Almox Qualidade'), ('almox_corte_estamparia', 'Almox Corte e Estamparia'), ('almox_prototipos', 'Almox Protótipos'), ('almox_serra', 'Almox Serra')], max_length=50)),
                ('peca', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='etapas', to='cadastro.pecas')),
            ],
        ),
    ]
