# Generated by Django 4.2.15 on 2024-12-11 09:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cadastro', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='blocorecursos',
            name='obs',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
    ]
