# Generated by Django 4.2.15 on 2024-12-11 09:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cadastro', '0003_alter_recursos_codigo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recursos',
            name='codigo',
            field=models.CharField(max_length=100, unique=True),
        ),
        migrations.AlterField(
            model_name='recursos',
            name='descricao',
            field=models.CharField(max_length=255),
        ),
    ]
