# Generated by Django 4.2.15 on 2024-12-19 09:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cadastro', '0004_alter_recursos_codigo_alter_recursos_descricao'),
    ]

    operations = [
        migrations.AddField(
            model_name='blocorecursos',
            name='cx_acess',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='blocorecursos',
            name='flag_romaneio',
            field=models.BooleanField(default=False),
        ),
    ]
